# @package _global_
defaults:
  - override /dataset: mnist
  - override /model: lite

diffusion:
  timesteps: 128
  schedule: cosine
  cfg: # classifier free guidance
    enable: true
    scale: 3.0
ema:
  enable: false
n_epochs: 300
fwd_dtype: float32
batch_size: 128
dataloader:
  workers: 2
logging:
  log_dir: ./logs
  wandb:
    enable: true
    project: diffusion