# @package _global_
defaults:
  - override /dataset: mnist
  - override /model: lite

diffusion:
  timesteps: 128
  schedule: cosine
  cfg: # classifier free guidance
    enable: true
    scale: 3.0
n_epochs: 300
device_type: auto
batch_size: 32
torch_compile: false
enable_tf32: false
fwd_dtype: float32
dataloader:
  workers: 0
  pin_memory: false
logging:
  log_dir: ./logs
  wandb:
    enable: false
    project: diffusion