# @package _global_
defaults:
  - override /dataset: mnist
  - override /model: lite

diffusion:
  timesteps: 128
  schedule: cosine
  cfg: # classifier free guidance
    enable: true
    scale: 3.0
n_epochs: 300
dataloader:
  workers: 2
  pin_memory: false
logging:
  log_dir: ./logs
  wandb:
    enable: false
    project: diffusion